name: mega_test
description: Teste da Mega Sistemas Corporativos


environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  http: ^0.11.3+16
  json_annotation: ^0.2.5
  image_picker: ^0.4.10
  cloud_firestore: ^0.7.3
  firebase_storage: ^1.0.3

  #Externals libs
  flutter_slidable: ^0.4.7
  flutter_masked_text: ^0.6.0

dev_dependencies:
  build_runner: ^0.9.0
  json_serializable: ^0.5.4

  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/images/icone-mega.png
    - assets/images/logo-mega-sistemas.png
    - assets/images/MegaLOGO.png
    - assets/images/user.png

  fonts:
      - family: Intelo
        fonts:
          - asset: assets/fonts/Intelo-Light.ttf
          - asset: assets/fonts/Intelo-Regular.ttf
          - asset: assets/fonts/Intelo-Bold.ttf
